
project:
  type: website
  output-dir: docs

website:
  title: "Ramesh Dulal"
  navbar:
    right:
      - href: index.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: personal.qmd
        text: Personal
  page-footer:
    center: |
      <div class="social-footer">
        <a href="https://github.com/Dulal-Ramesh" target="_blank" rel="noopener">
          <i class="fa-brands fa-github"></i>
        </a>
        <a href="https://x.com/RameshhDulal" target="_blank" rel="noopener">
          <i class="fa-brands fa-square-x-twitter"></i>
        </a>
        <a href="https://www.linkedin.com/in/ramesh-dulal-979574ab/" target="_blank" rel="noopener">
          <i class="fa-brands fa-linkedin"></i>
        </a>
        <a href="https://scholar.google.com/citations?user=P6ZYvyQAAAAJ&hl=en" target="_blank" rel="noopener">
          <i class="fa-solid fa-graduation-cap"></i>
        </a>
      </div>

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
